import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.dependency.analysis)
}

kotlin {
    sourceCompatibility = JvmTarget.fromTarget(libs.versions.java.get()).target
    targetCompatibility = JvmTarget.fromTarget(libs.versions.java.get()).target
}

android {
    namespace 'com.woocommerce.android.konsist.tests'

    compileOptions {
        sourceCompatibility libs.versions.java.get()
        targetCompatibility libs.versions.java.get()
    }

    defaultConfig {
        minSdkVersion gradle.ext.minSdkVersion
        targetSdkVersion gradle.ext.targetSdkVersion
        compileSdk gradle.ext.compileSdkVersion
    }
}

dependencies {
    implementation(libs.androidx.lifecycle.viewmodel.savedstate)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.google.dagger.compiler)
    implementation(libs.google.dagger.hilt.compiler)
    implementation(libs.google.dagger.hilt.android.main)
    implementation(libs.google.dagger.hilt.android.testing)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui.tooling.main)

    testImplementation(libs.junit)
    testImplementation(libs.konsist)
}

// See: https://docs.konsist.lemonappdev.com/advanced/isolate-konsist-tests#solution-1-module-is-always-out-of-date
tasks.withType(Test).configureEach {
    outputs.upToDateWhen { false }
}
