package com.woocommerce.android.ui.compose.designsystem.foundation

import androidx.compose.material3.ColorScheme

internal fun WooColors.toMaterialColorScheme(): ColorScheme = ColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = secondary,
    onPrimaryContainer = onSecondary,
    inversePrimary = primary,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondary,
    onSecondaryContainer = onSecondary,
    tertiary = secondary,
    onTertiary = onSecondary,
    tertiaryContainer = secondary,
    onTertiaryContainer = onSecondary,
    background = background.section,
    onBackground = background.onSection,
    surface = surface.default,
    onSurface = surface.onDefault,
    surfaceVariant = background.sectionVariant,
    onSurfaceVariant = surface.onVariant,
    surfaceTint = primary,
    inverseSurface = surface.inverted,
    inverseOnSurface = surface.onInverted,
    error = status.error,
    onError = onPrimary,
    errorContainer = status.errorContainer,
    onErrorContainer = status.onErrorContainer,
    outline = outline,
    outlineVariant = outlineVariant,
    scrim = overlay.overlay50,
    surfaceBright = surface.default,
    surfaceDim = background.section,
    surfaceContainer = background.section,
    surfaceContainerHigh = surface.default,
    surfaceContainerHighest = surface.default,
    surfaceContainerLow = background.sectionVariant,
    surfaceContainerLowest = surface.default,
    primaryFixed = primary,
    primaryFixedDim = secondary,
    onPrimaryFixed = onPrimary,
    onPrimaryFixedVariant = onSecondary,
    secondaryFixed = secondary,
    secondaryFixedDim = secondary,
    onSecondaryFixed = onSecondary,
    onSecondaryFixedVariant = onSecondary,
    tertiaryFixed = secondary,
    tertiaryFixedDim = secondary,
    onTertiaryFixed = onSecondary,
    onTertiaryFixedVariant = onSecondary,
)
