plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
    alias(libs.plugins.dependency.analysis)
}

android {
    namespace = 'com.woocommerce.commons'
    compileSdk = gradle.ext.compileSdkVersion

    defaultConfig {
        minSdk = gradle.ext.minSdkVersion
        targetSdk = gradle.ext.targetSdkVersion
    }

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    lintOptions {
        baseline file("lint-baseline.xml")
    }

    testFixtures.enable = true
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.compose.ui.main)
    implementation(libs.glassfish.javax.annotation)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.automattic.tracks.crashlogging)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.preference.main)
    implementation(libs.eventbus.android)
    implementation(libs.google.dagger.hilt.core)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.wordpress.utils)
    implementation(libs.apache.commons.text)
    implementation(project(":libs:fluxc"))
    implementation(project(":libs:fluxc-plugin"))

    ksp(libs.google.dagger.hilt.compiler)

    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.assertj.core)
    testImplementation(libs.junit)
    testImplementation(libs.mockito.kotlin)
    testRuntimeOnly(libs.androidx.arch.core.testing)
    testImplementation(libs.androidx.lifecycle.runtime.testing)

    testFixturesImplementation(platform(libs.androidx.compose.bom))
    testFixturesImplementation(libs.androidx.compose.ui.main)
    testFixturesCompileOnly(libs.kotlinx.coroutines.test)
    testFixturesCompileOnly(libs.junit)
    testFixturesCompileOnly(libs.mockito.kotlin)
    testFixturesCompileOnly(libs.androidx.arch.core.testing)
}
