plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.dependency.analysis)
}

android {
    namespace = 'com.woocommerce.commons'
    compileSdk = gradle.ext.compileSdkVersion

    defaultConfig {
        minSdk = gradle.ext.minSdkVersion
        targetSdk = gradle.ext.targetSdkVersion
    }

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    testFixtures.enable = true
}

dependencies {
    implementation(libs.androidx.annotation)
    implementation("javax.inject:javax.inject:1")
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.automattic.tracks.crashlogging)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.google.dagger.hilt.android.main)
    implementation(libs.wordpress.utils)

    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.assertj.core)
    testImplementation(libs.junit)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.androidx.arch.core.testing)
    testImplementation(libs.androidx.lifecycle.runtime.testing)

    testFixturesCompileOnly(libs.kotlinx.coroutines.test)
    testFixturesCompileOnly(libs.junit)
    testFixturesCompileOnly(libs.mockito.kotlin)
    testFixturesCompileOnly(libs.androidx.arch.core.testing)
}
