import com.automattic.android.measure.reporters.InternalA8cCiReporter
import com.automattic.android.measure.reporters.RemoteBuildCacheMetricsReporter
import com.automattic.android.measure.reporters.SlowSlowTasksMetricsReporter
import io.gitlab.arturbosch.detekt.Detekt
import io.sentry.android.gradle.extensions.InstrumentationFeature
import io.sentry.android.gradle.tasks.SentryCliExecTask
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.detekt)
    alias(libs.plugins.automattic.measure.builds)
    alias(libs.plugins.dependency.analysis)
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.test) apply false
    alias(libs.plugins.kotlin.compose).apply(false)
    alias(libs.plugins.compose.screenshot) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.android.legacy.kapt) apply false
    alias(libs.plugins.google.dagger.hilt) apply false
    alias(libs.plugins.androidx.navigation.safeargs) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.sentry) apply false
    alias(libs.plugins.room) apply false
}

ext {
    secretProperties = gradle.ext.secretProperties
    developerProperties = gradle.ext.developerProperties
}

measureBuilds {
    enable = secretProperties.getProperty("measureBuildsEnabled", "false").toBoolean()
    onBuildMetricsReadyListener { report ->
        SlowSlowTasksMetricsReporter.report(report)
        RemoteBuildCacheMetricsReporter.report(report)
        InternalA8cCiReporter.reportBlocking(
                report,
                "woocommerce",
                secretProperties.getProperty("appsMetricsToken")
        )
    }
    attachGradleScanId = false
}

allprojects {
    apply plugin: libs.plugins.detekt.get().pluginId

    tasks.withType(KotlinCompile).configureEach {
        compilerOptions {
            jvmTarget = JvmTarget.fromTarget(libs.versions.java.get())
            allWarningsAsErrors = true
            optIn.add("kotlin.RequiresOptIn")
            freeCompilerArgs.addAll([
                    "-jvm-default=enable",
                    "-Xwarning-level=USELESS_CAST:disabled"
            ])
        }
    }
}

subprojects {
    plugins.withType(com.android.build.gradle.AppPlugin) {
        android {
            lintOptions {
                sarifReport = gradle.ext.isCi
                baseline file("lint-baseline.xml")
            }
        }
        dependencies {
            lintChecks(libs.wordpress.lint)
            lintChecks(libs.android.security.lint)
        }
    }
    plugins.withType(com.android.build.gradle.LibraryPlugin) {
        dependencies {
            lintChecks(libs.wordpress.lint)
            lintChecks(libs.android.security.lint)
        }
    }
    plugins.withId(libs.plugins.sentry.get().pluginId) {
        def sentryAuthToken = providers.environmentVariable("SENTRY_AUTH_TOKEN").orNull?.trim() ?: null
        def shouldUploadToSentry = gradle.ext.isCi
                && !providers.gradleProperty("skipSentryUpload").orNull?.toBoolean()

        sentry {
            org = "a8c"
            authToken = sentryAuthToken

            includeProguardMapping = shouldUploadToSentry
            includeSourceContext = shouldUploadToSentry
            autoUploadSourceContext = true
            tracingInstrumentation {
                enabled = true
                features = [InstrumentationFeature.DATABASE]
                logcat {
                    enabled = false
                }
            }
            autoInstallation {
                enabled = false
            }
            includeDependenciesReport = false
            /* Sentry won't send source context or add performance instrumentations for debug builds
            so we can save build times. Sending events will still work in debug builds
            (if enabled in WCCrashLoggingDataProvider).
            */
            ignoredBuildTypes = ["debug"]
        }

        tasks.withType(SentryCliExecTask).configureEach {
            doFirst {
                if (sentryAuthToken == null) {
                    throw new GradleException("SENTRY_AUTH_TOKEN is not set (or is blank). " +
                            "Export it to upload debug files to Sentry, " +
                            "or pass -PskipSentryUpload=true to skip the upload.")
                }
            }
        }
    }
}

tasks.register("detektAll", Detekt) {
    description = "Custom DETEKT build for all modules"
    parallel = true
    ignoreFailures = false
    buildUponDefaultConfig = true
    setSource(file(projectDir))
    baseline.set(file("$rootDir/config/detekt/baseline.xml"))
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    include("**/*.kt")
    exclude("**/resources/**", "**/build/**", "/vendor/**")

    reports {
        xml.required.set(true)
        html.required.set(true)
        txt.required.set(false)
    }
}

dependencies {
    detektPlugins(libs.detekt.formatting)
    detektPlugins project(':libs:detektrules')
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

/**
 * Copies git-hooks from the `tools/team-props/git-hooks' directory to the `.git/hooks` folder
 * at the root of this project.
 */
tasks.register("installGitHooks", Copy) {
    println "Copying git-hooks scripts from tools/team-props/git-hooks to .git/hooks"
    from new File(rootProject.rootDir, 'tools/team-props/git-hooks')
    into { new File(rootProject.rootDir, '.git/hooks') }
    fileMode 0777
}

apply from: './config/gradle/jacoco.gradle'
