package com.woocommerce.commons

enum class WearAnalyticsEvent {
    WATCH_STORE_DATA_REQUESTED,
    WATCH_STORE_DATA_SUCCEEDED,
    WATCH_STORE_DATA_FAILED,
    WATCH_STATS_DATA_REQUESTED,
    WATCH_STATS_DATA_SUCCEEDED,
    WATCH_STATS_DATA_FAILED,
    WATCH_ORDERS_LIST_DATA_REQUESTED,
    WATCH_ORDERS_LIST_DATA_SUCCEEDED,
    WATCH_ORDERS_LIST_DATA_FAILED,
    WATCH_ORDER_DETAILS_DATA_REQUESTED,
    WATCH_ORDER_DETAILS_DATA_SUCCEEDED,
    WATCH_ORDER_DETAILS_DATA_FAILED,
    WATCH_APP_OPENED,
    WATCH_ORDERS_LIST_OPENED,
    WATCH_ORDER_DETAILS_OPENED
}
