package com.woocommerce.commons

enum class WearAnalyticsEvent {
    // App events
    WATCH_APP_OPENED,

    // Store events
    WATCH_STORE_DATA_REQUESTED,
    WATCH_STORE_DATA_SUCCEEDED,
    WATCH_STORE_DATA_FAILED,

    // Stats events
    WATCH_STATS_DATA_REQUESTED,
    WATCH_STATS_DATA_SUCCEEDED,
    WATCH_STATS_DATA_FAILED,

    // Orders list events
    WATCH_ORDERS_LIST_OPENED,
    WATCH_ORDERS_LIST_DATA_REQUESTED,
    WATCH_ORDERS_LIST_DATA_SUCCEEDED,
    WATCH_ORDERS_LIST_DATA_FAILED,

    // Order details events
    WATCH_ORDER_DETAILS_OPENED,
    WATCH_ORDER_DETAILS_DATA_REQUESTED,
    WATCH_ORDER_DETAILS_DATA_SUCCEEDED,
    WATCH_ORDER_DETAILS_DATA_FAILED,

    // Data sync events
    WATCH_DATA_REQUESTED_FROM_PHONE,
    WATCH_DATA_REQUESTED_FROM_STORE
}
