plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.google.dagger.hilt)
    alias(libs.plugins.dependency.analysis)
}

android {
    namespace = "com.woocommerce.android.aiassistant"

    defaultConfig {
        minSdkVersion gradle.ext.minSdkVersion
        targetSdkVersion gradle.ext.targetSdkVersion
        compileSdk = gradle.ext.compileSdkVersion
    }

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }
}

dependencies {
    implementation(project(":libs:ai-assistant:core"))

    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.squareup.okhttp3)
    implementation(libs.squareup.okhttp3.sse)
    implementation(libs.google.dagger.hilt.android.main)

    ksp(libs.google.dagger.hilt.compiler)

    testImplementation(libs.junit)
    testImplementation(libs.assertj.core)
    testImplementation(libs.kotlinx.coroutines.test)
}
