# Nodes with values to reuse in the pipeline.
common_params:
  - &ruby_image "public.ecr.aws/docker/library/ruby:3.2.2"

agents:
  queue: "default"

steps:
  - label: "☢️ Danger - PR Check"
    command: .buildkite/commands/danger-pr-check.sh
    plugins:
      - docker#v5.8.0:
          image: *ruby_image
          propagate-environment: true
          environment:
            - "DANGER_GITHUB_API_TOKEN"
    if: "build.pull_request.id != null"
    retry:
      manual:
        permit_on_passed: true
