# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "💾 Restore and Diff Merged Manifest"
    command: |
      .buildkite/commands/restore-cache.sh
      ./gradlew assembleJalapenoDebug
      ".buildkite/commands/restore-merged-manifest.sh" "WooCommerce"
      "comment_with_manifest_diff" "WooCommerce"
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/reports/diff_manifest/*"
