# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.1.0

steps:
  - label: "checkstyle"
    command: |
      echo "--- 🧹 Linting"
      cp -v gradle.properties-example gradle.properties
      ./gradlew checkstyle
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "detekt"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintJalapenoDebug
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Unit tests"
    command: |
      echo "--- 🧪 Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testJalapenoDebug
      ./gradlew lib:cardreader:testDebug
    plugins: *common_plugins

  - label: "Ensure Screenshot Tests Build"
    command: |
      echo "--- ⚒️ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleJalapenoDebugAndroidTest
    plugins: *common_plugins

  - label: "🛠 Installable Build"
    command: | 
      echo $BUILDKITE_PULL_REQUEST
      ".buildkite/commands/installable-build.sh"
      #if: "build.pull_request.id != null || build.pull_request.draft"
    plugins: *common_plugins
