# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.17.0

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "detekt"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintJalapenoDebug
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Dependency Tree Diff"
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/commands/dependency-tree-diff.sh
    if: build.pull_request.id != null
    plugins: *common_plugins

  - label: "Unit tests"
    key: "unit_tests"  
    command: .buildkite/commands/run-unit-tests.sh
    plugins: 
      - automattic/a8c-ci-toolkit#2.17.0
      - test-collector#v1.8.0:
          files: "**/build/test-results/*/*.xml"
          format: "junit"
          api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT_TESTS"
    artifact_paths:
      - "**/build/test-results/*/*.xml"

  - label: "Ensure Screenshot Tests Build"
    command: |
      echo "--- ⚒️ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleJalapenoDebugAndroidTest
    plugins: *common_plugins

  - label: "🛠 Installable Build"
    command: ".buildkite/commands/installable-build.sh"
    if: build.pull_request.id != null
    plugins: *common_plugins

  - label: "Instrumented tests"
    key: "instrumented_tests"
    command: .buildkite/commands/run-instrumented-tests.sh
    plugins: *common_plugins
    artifact_paths:
      - "**/build/instrumented-tests/**/*"

  - label: "🔍 Instrumented Tests Analytics"
    command: buildkite-agent artifact download '**/test_result_1.xml' . --step "instrumented_tests"
    depends_on:
      - "instrumented_tests"
    plugins:
      - test-collector#v1.8.0:
          files: "**/test_result_1.xml"
          format: "junit"
          api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS"
