# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  - label: "Test mac-metal queue"
    command: |
      env
      echo "Hello, world!"
      aws --version
    plugins: [$CI_TOOLKIT]
    agents:
      queue: "mac-metal"

