# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &ci_toolkit
    automattic/a8c-ci-toolkit#3.0.1
  - &test_collector
    test-collector#v1.10.0
  - &test_collector_common_params
      files: "WooCommerce/build/buildkite-test-analytics/*.xml"
      format: "junit"

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [*ci_toolkit]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Starting Danger..."
    command: "buildkite-agent pipeline upload .buildkite/danger.yml"
    agents:
      queue: "default"

  - label: "detekt"
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    plugins: [*ci_toolkit]
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintJalapenoDebug
    plugins: [*ci_toolkit]
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Dependency Tree Diff"
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/commands/dependency-tree-diff.sh
    if: build.pull_request.id != null
    plugins: [*ci_toolkit]

  - label: "Unit tests"
    command: .buildkite/commands/run-unit-tests.sh
    plugins:
      - *ci_toolkit
      - *test_collector :
          <<: *test_collector_common_params
          api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT_TESTS"
    artifact_paths:
      - "**/build/test-results/*/*.xml"

  - label: "Ensure Screenshot Tests Build"
    command: |
      echo "--- âš’ï¸ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleJalapenoDebugAndroidTest
    plugins: [*ci_toolkit]

  - label: "ðŸ›  Prototype Build"
    command: ".buildkite/commands/prototype-build.sh"
    if: build.pull_request.id != null
    plugins: [*ci_toolkit]

  - label: "Instrumented tests"
    command: .buildkite/commands/run-instrumented-tests.sh
    plugins:
      - *ci_toolkit
      - *test_collector :
          <<: *test_collector_common_params
          api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS"
    artifact_paths:
      - "**/build/instrumented-tests/**/*"
