# This pipeline is meant to be run via the Buildkite API, and is
# only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#3.0.1

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    priority: 1
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "🛠 Release Build ($APP_TO_BUILD)"
    command: |
      ".buildkite/commands/release-build.sh" "${APP_TO_BUILD}"
    priority: 1
    plugins: *common_plugins
    notify:
      - slack: "#build-and-ship"
