# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# This pipeline is meant to be run via the Buildkite API, and is
# only used for release builds

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    priority: 1
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "🛠 Release Build (Mobile App)"
    command: |
      ".buildkite/commands/release-build.sh" "WooCommerce"
    priority: 1
    plugins: [$CI_TOOLKIT]
    notify:
      - slack: "#build-and-ship"

  - label: "🛠 Release Build (Wear App)"
    command: |
      ".buildkite/commands/release-build.sh" "WooCommerce-Wear"
    priority: 1
    plugins: [$CI_TOOLKIT]
    if: build.env('INCLUDE_WEAR_APP') == "true"
    notify:
      - slack: "#build-and-ship"
    retry:
      manual:
        allowed: false
