#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# "git-crypt-unlock" branch / https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/195
export CI_TOOLKIT="automattic/a8c-ci-toolkit#e79b4e5cba54576e4dd2a4941714e9dd2f7c687c"
export TEST_COLLECTOR="test-collector#v1.10.1"
export CLAUDE_PLUGIN="claude-summarize#v1.1.0"
