#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#9ab2426db86e5a096938340800de26ecd5f7acfb" # https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/195
export TEST_COLLECTOR="test-collector#v1.10.1"
export CLAUDE_PLUGIN="claude-summarize#v1.1.0"
