#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#a960f3bdd9458095a971116c6bdbae0b57f3ed11"
export TEST_COLLECTOR="test-collector#v1.10.1"
