package com.woocommerce.android.ui.login.storecreation.countrypicker

import javax.inject.Inject

class LocalCountriesRepository @Inject constructor() {
    fun getLocalCountries(): Map<String, String> = countriesMap
}

private val countriesMap = mapOf(
    "AX" to "&#197;land Islands",
    "AF" to "Afghanistan",
    "AL" to "Albania",
    "DZ" to "Algeria",
    "AS" to "American Samoa",
    "AD" to "Andorra",
    "AO" to "Angola",
    "AI" to "Anguilla",
    "AQ" to "Antarctica",
    "AG" to "Antigua and Barbuda",
    "AR" to "Argentina",
    "AM" to "Armenia",
    "AW" to "Aruba",
    "AU" to "Australia",
    "AT" to "Austria",
    "AZ" to "Azerbaijan",
    "BS" to "Bahamas",
    "BH" to "Bahrain",
    "BD" to "Bangladesh",
    "BB" to "Barbados",
    "BY" to "Belarus",
    "PW" to "Belau",
    "BE" to "Belgium",
    "BZ" to "Belize",
    "BJ" to "Benin",
    "BM" to "Bermuda",
    "BT" to "Bhutan",
    "BO" to "Bolivia",
    "BQ" to "Bonaire, Saint Eustatius and Saba",
    "BA" to "Bosnia and Herzegovina",
    "BW" to "Botswana",
    "BV" to "Bouvet Island",
    "BR" to "Brazil",
    "IO" to "British Indian Ocean Territory",
    "VG" to "British Virgin Islands",
    "BN" to "Brunei",
    "BG" to "Bulgaria",
    "BF" to "Burkina Faso",
    "BI" to "Burundi",
    "KH" to "Cambodia",
    "CM" to "Cameroon",
    "CA" to "Canada",
    "CV" to "Cape Verde",
    "KY" to "Cayman Islands",
    "CF" to "Central African Republic",
    "TD" to "Chad",
    "CL" to "Chile",
    "CN" to "China",
    "CX" to "Christmas Island",
    "CC" to "Cocos (Keeling) Islands",
    "CO" to "Colombia",
    "KM" to "Comoros",
    "CG" to "Congo (Brazzaville)",
    "CD" to "Congo (Kinshasa)",
    "CK" to "Cook Islands",
    "CR" to "Costa Rica",
    "HR" to "Croatia",
    "CU" to "Cuba",
    "CW" to "Cura&ccedil;ao",
    "CY" to "Cyprus",
    "CZ" to "Czech Republic",
    "DK" to "Denmark",
    "DJ" to "Djibouti",
    "DM" to "Dominica",
    "DO" to "Dominican Republic",
    "EC" to "Ecuador",
    "EG" to "Egypt",
    "SV" to "El Salvador",
    "GQ" to "Equatorial Guinea",
    "ER" to "Eritrea",
    "EE" to "Estonia",
    "ET" to "Ethiopia",
    "FK" to "Falkland Islands",
    "FO" to "Faroe Islands",
    "FJ" to "Fiji",
    "FI" to "Finland",
    "FR" to "France",
    "GF" to "French Guiana",
    "PF" to "French Polynesia",
    "TF" to "French Southern Territories",
    "GA" to "Gabon",
    "GM" to "Gambia",
    "GE" to "Georgia",
    "DE" to "Germany",
    "GH" to "Ghana",
    "GI" to "Gibraltar",
    "GR" to "Greece",
    "GL" to "Greenland",
    "GD" to "Grenada",
    "GP" to "Guadeloupe",
    "GU" to "Guam",
    "GT" to "Guatemala",
    "GG" to "Guernsey",
    "GN" to "Guinea",
    "GW" to "Guinea-Bissau",
    "GY" to "Guyana",
    "HT" to "Haiti",
    "HM" to "Heard Island and McDonald Islands",
    "HN" to "Honduras",
    "HK" to "Hong Kong",
    "HU" to "Hungary",
    "IS" to "Iceland",
    "IN" to "India",
    "ID" to "Indonesia",
    "IR" to "Iran",
    "IQ" to "Iraq",
    "IE" to "Ireland",
    "IM" to "Isle of Man",
    "IL" to "Israel",
    "IT" to "Italy",
    "CI" to "Ivory Coast",
    "JM" to "Jamaica",
    "JP" to "Japan",
    "JE" to "Jersey",
    "JO" to "Jordan",
    "KZ" to "Kazakhstan",
    "KE" to "Kenya",
    "KI" to "Kiribati",
    "KW" to "Kuwait",
    "KG" to "Kyrgyzstan",
    "LA" to "Laos",
    "LV" to "Latvia",
    "LB" to "Lebanon",
    "LS" to "Lesotho",
    "LR" to "Liberia",
    "LY" to "Libya",
    "LI" to "Liechtenstein",
    "LT" to "Lithuania",
    "LU" to "Luxembourg",
    "MO" to "Macao S.A.R., China",
    "MK" to "Macedonia",
    "MG" to "Madagascar",
    "MW" to "Malawi",
    "MY" to "Malaysia",
    "MV" to "Maldives",
    "ML" to "Mali",
    "MT" to "Malta",
    "MH" to "Marshall Islands",
    "MQ" to "Martinique",
    "MR" to "Mauritania",
    "MU" to "Mauritius",
    "YT" to "Mayotte",
    "MX" to "Mexico",
    "FM" to "Micronesia",
    "MD" to "Moldova",
    "MC" to "Monaco",
    "MN" to "Mongolia",
    "ME" to "Montenegro",
    "MS" to "Montserrat",
    "MA" to "Morocco",
    "MZ" to "Mozambique",
    "MM" to "Myanmar",
    "NA" to "Namibia",
    "NR" to "Nauru",
    "NP" to "Nepal",
    "NL" to "Netherlands",
    "NC" to "New Caledonia",
    "NZ" to "New Zealand",
    "NI" to "Nicaragua",
    "NE" to "Niger",
    "NG" to "Nigeria",
    "NU" to "Niue",
    "NF" to "Norfolk Island",
    "KP" to "North Korea",
    "MP" to "Northern Mariana Islands",
    "NO" to "Norway",
    "OM" to "Oman",
    "PK" to "Pakistan",
    "PS" to "Palestinian Territory",
    "PA" to "Panama",
    "PG" to "Papua New Guinea",
    "PY" to "Paraguay",
    "PE" to "Peru",
    "PH" to "Philippines",
    "PN" to "Pitcairn",
    "PL" to "Poland",
    "PT" to "Portugal",
    "PR" to "Puerto Rico",
    "QA" to "Qatar",
    "RE" to "Reunion",
    "RO" to "Romania",
    "RU" to "Russia",
    "RW" to "Rwanda",
    "ST" to "S&atilde;o Tom&eacute; and Pr&iacute;ncipe",
    "BL" to "Saint Barth&eacute;lemy",
    "SH" to "Saint Helena",
    "KN" to "Saint Kitts and Nevis",
    "LC" to "Saint Lucia",
    "SX" to "Saint Martin (Dutch part)",
    "MF" to "Saint Martin (French part)",
    "PM" to "Saint Pierre and Miquelon",
    "VC" to "Saint Vincent and the Grenadines",
    "WS" to "Samoa",
    "SM" to "San Marino",
    "SA" to "Saudi Arabia",
    "SN" to "Senegal",
    "RS" to "Serbia",
    "SC" to "Seychelles",
    "SL" to "Sierra Leone",
    "SG" to "Singapore",
    "SK" to "Slovakia",
    "SI" to "Slovenia",
    "SB" to "Solomon Islands",
    "SO" to "Somalia",
    "ZA" to "South Africa",
    "GS" to "South Georgia/Sandwich Islands",
    "KR" to "South Korea",
    "SS" to "South Sudan",
    "ES" to "Spain",
    "LK" to "Sri Lanka",
    "SD" to "Sudan",
    "SR" to "Suriname",
    "SJ" to "Svalbard and Jan Mayen",
    "SZ" to "Swaziland",
    "SE" to "Sweden",
    "CH" to "Switzerland",
    "SY" to "Syria",
    "TW" to "Taiwan",
    "TJ" to "Tajikistan",
    "TZ" to "Tanzania",
    "TH" to "Thailand",
    "TL" to "Timor-Leste",
    "TG" to "Togo",
    "TK" to "Tokelau",
    "TO" to "Tonga",
    "TT" to "Trinidad and Tobago",
    "TN" to "Tunisia",
    "TR" to "Turkey",
    "TM" to "Turkmenistan",
    "TC" to "Turks and Caicos Islands",
    "TV" to "Tuvalu",
    "UG" to "Uganda",
    "UA" to "Ukraine",
    "AE" to "United Arab Emirates",
    "GB" to "United Kingdom (UK)",
    "US" to "United States (US)",
    "UM" to "United States (US) Minor Outlying Islands",
    "VI" to "United States (US) Virgin Islands",
    "UY" to "Uruguay",
    "UZ" to "Uzbekistan",
    "VU" to "Vanuatu",
    "VA" to "Vatican",
    "VE" to "Venezuela",
    "VN" to "Vietnam",
    "WF" to "Wallis and Futuna",
    "EH" to "Western Sahara",
    "YE" to "Yemen",
    "ZM" to "Zambia",
    "ZW" to "Zimbabwe"
)
