[versions]
agp = '8.13.2'
android-desugar = '2.1.5'
android-security-lint = '1.0.4'
androidx-activity = '1.13.0'
androidx-appcompat = '1.7.1'
androidx-arch-core = '2.2.0'
androidx-annotation = '1.10.0'
androidx-browser = '1.10.0'
androidx-camera = '1.5.3'
androidx-cardview = '1.0.0'
androidx-compose-bom = '2025.11.01'
androidx-constraintlayout-compose = '1.0.1'
androidx-constraintlayout-main = '2.2.1'
androidx-core-main = '1.17.0'
androidx-core-splashscreen = '1.2.0'
androidx-credentials = '1.5.0'
androidx-datastore = '1.2.1'
androidx-exifinterface = "1.4.2"
androidx-fragment = '1.8.9'
androidx-hilt = '1.3.0'
androidx-lifecycle = '2.10.0'
androidx-navigation = '2.9.5'
androidx-paging-runtime = "2.1.2"
androidx-preference = '1.2.1'
androidx-recyclerview-main = '1.4.0'
androidx-recyclerview-selection = '1.1.0'
androidx-room = "2.8.4"
androidx-security-crypto = "1.1.0"
androidx-test-core = '1.7.0'
androidx-test-espresso = '3.7.0'
androidx-test-ext = '1.3.0'
androidx-test-rules = '1.7.0'
androidx-test-runner = '1.7.0'
androidx-test-orchestrator = '1.6.1'
androidx-test-uiautomator = '2.3.0'
androidx-transition = '1.7.0'
androidx-wear-compose = '1.4.0'
androidx-wear-protolayout = '1.2.1'
androidx-wear-tooling = '1.0.0'
androidx-wear-watchface = '1.3.0'
androidx-work = '2.11.2'
apache-commons-text = '1.15.0'
apache-http-client-android = '4.3.5.1'
apache-http-core = '4.4.16'
automattic-about = '1.7.1'
automattic-encryptedlogging = '1.1.2'
automattic-measure-builds = '3.2.2'
automattic-tracks = '6.0.8'
assertj = '3.27.3'
bumptech-glide = '5.0.9'
cashapp-turbine = '1.2.1'
coil = '2.7.0'
commons-fileupload = '1.6.0'
dependency-analysis = '3.14.1'
detekt = '1.23.8'
eventbus = "3.3.1"
facebook-shimmer = '0.5.0'
fastlane-screengrab = '2.1.1'
fladle = '0.21.0'
glassfish-javax-annotation = "10.0-b28"
google-autoService = "1.1.1"
google-dagger = "2.58"
google-firebase-bom = '34.5.0'
google-gson = '2.14.0'
google-guava = '33.6.0-android'
google-horologist = '0.7.15'
google-material = '1.14.0'
google-compose-material3 = '1.4.0'
google-mlkit-barcode-scanning = '17.3.0'
google-mlkit-subject-segmentation = '16.0.0-beta1'
google-mlkit-text-recognition = '16.0.1'
google-play-app-update = '2.1.0'
google-play-review = '2.0.2'
google-play-ageSignals = "0.0.3"
google-play-services-auth = '21.6.0'
google-play-services-code-scanner = '16.1.0'
google-play-services-wearable = '20.0.1'
google-protobuf-plugin = '0.10.0'
google-protobuf-library = '4.35.1'
google-services = '4.4.4'
google-zxing = '3.5.4'
gravatar = '2.5.1'
jackson = '2.18.8'
java = '11'
jetty = '9.4.57.v20241219'
json-path = '2.9.0'
json-smart = '2.6.0'
junit = '4.13.2'
lottie = '6.7.1'
kotlin = '2.3.21'
kotlinx-coroutines = '1.11.0'
kotlinx-serialization = '1.11.0'
ksp = '2.3.9'
mockito-kotlin = '6.3.0'
mpandroidchart = 'v3.1.0'
photoview = '2.3.0'
robolectric = "4.16.1"
sentry = '6.11.0'
screenshot = '0.0.1-alpha15'
squareup-javapoet = "1.13.0"
squareup-leakcanary = '2.14'
squareup-okhttp3 = "5.3.2"
stripe-terminal = '5.6.0'
swiperefreshlayout = "1.2.0"
tinder-statemachine = '0.2.0'
volley = "1.2.1"
wellsql = "2.0.0"
wiremock = '2.26.3'
wordpress-aztec = 'v2.1.7'
wordpress-libaddressinput = '0.0.2'
wordpress-lint = "2.2.0"
wordpress-mediapicker = '0.3.5'
wordpress-utils = '3.15.0'
zendesk = '5.5.3'

[libraries]
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugar" }
android-security-lint = { group = "com.android.security.lint", name = "lint", version.ref = "android-security-lint" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidx-arch-core" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidx-camera" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardview" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-animation-main = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-material-main = { group = "androidx.compose.material", name = "material" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-main = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling-main = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3-android" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-constraintlayout-main = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout-main" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-main" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-credentials-main = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-service-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
androidx-datastore-main = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-lifecycle-viewmodel-compose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "androidx-hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "androidx-hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-testing = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "androidx-navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "androidx-navigation" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging-runtime" }
androidx-preference-main = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview-main = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview-main" }
androidx-recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "androidx-recyclerview-selection" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx-security-crypto" }
androidx-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-main-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-main-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-main-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-transition = { group = "androidx.transition", name = "transition", version.ref = "androidx-transition" }
androidx-wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "androidx-wear-compose" }
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "androidx-wear-compose" }
androidx-wear-protolayout-expression = { group = "androidx.wear.protolayout", name = "protolayout-expression", version.ref = "androidx-wear-protolayout" }
androidx-wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "androidx-wear-tooling" }
androidx-wear-watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "androidx-wear-watchface" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "apache-commons-text" }
apache-http-client-android = { group = "org.apache.httpcomponents", name = "httpclient-android", version.ref = "apache-http-client-android" }
apache-http-core = { group = "org.apache.httpcomponents", name = "httpcore", version.ref = "apache-http-core" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
automattic-about = { group = "com.automattic", name = "about", version.ref = "automattic-about" }
automattic-eventhorizon = "com.automattic:eventhorizon:woocommerce-2026-05-22_09-49-18"
automattic-encryptedlogging = { group = "com.automattic", name = "encryptedlogging", version.ref = "automattic-encryptedlogging" }
automattic-tracks-android = { group = "com.automattic", name = "Automattic-Tracks-Android", version.ref = "automattic-tracks" }
automattic-tracks-experimentation = { group = "com.automattic.tracks", name = "experimentation", version.ref = "automattic-tracks" }
automattic-tracks-crashlogging = { group = "com.automattic.tracks", name = "crashlogging", version.ref = "automattic-tracks" }
bumptech-glide-main = { group = "com.github.bumptech.glide", name = "glide", version.ref = "bumptech-glide" }
bumptech-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "bumptech-glide" }
bumptech-glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "bumptech-glide" }
bumptech-glide-volley-integration = { group = "com.github.bumptech.glide", name = "volley-integration", version.ref = "bumptech-glide" }
cashapp-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "cashapp-turbine" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
commons-fileupload = { group = "commons-fileupload", name = "commons-fileupload", version.ref = "commons-fileupload" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
eventbus-android = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
eventbus-java = {group = "org.greenrobot", name = "eventbus-java", version.ref = "eventbus" }
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "facebook-shimmer" }
fastlane-screengrab = { group = "tools.fastlane", name = "screengrab", version.ref = "fastlane-screengrab" }
google-screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }
glassfish-javax-annotation = { module = "org.glassfish:javax.annotation", version.ref = "glassfish-javax-annotation" }
google-autoService = { module = "com.google.auto.service:auto-service", version.ref = "google-autoService" }
google-dagger = { module = "com.google.dagger:dagger", version.ref = "google-dagger" }
google-dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "google-dagger" }
google-dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "google-dagger" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
google-dagger-hilt-android-main = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger" }
google-dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "google-dagger" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-dagger" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "google-firebase-bom" }
google-firebase-config = { group = "com.google.firebase", name = "firebase-config" }
google-firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "google-gson" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "google-guava" }
google-horologist-compose-layout = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "google-horologist" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
google-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "google-compose-material3" }
google-mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "google-mlkit-barcode-scanning" }
google-mlkit-text-recognition-main = { group = "com.google.mlkit", name = "text-recognition", version.ref = "google-mlkit-text-recognition" }
google-mlkit-text-recognition-japanese = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-japanese", version.ref = "google-mlkit-text-recognition" }
google-mlkit-text-recognition-chinese = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-chinese", version.ref = "google-mlkit-text-recognition" }
google-mlkit-text-recognition-korean = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-korean", version.ref = "google-mlkit-text-recognition" }
google-play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "google-play-app-update" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "google-play-review" }
google-play-ageSignals = { module = "com.google.android.play:age-signals", version.ref = "google-play-ageSignals" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "google-play-services-auth" }
google-play-services-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "google-play-services-code-scanner" }
google-play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "google-play-services-wearable" }
google-play-services-mlkit-subject-segmentation = { group = "com.google.android.gms", name = "play-services-mlkit-subject-segmentation", version.ref = "google-mlkit-subject-segmentation" }
google-protobuf-kotlinlite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "google-protobuf-library" }
google-protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "google-protobuf-library" }
google-zxing-core = { group = "com.google.zxing", name = "core", version.ref = "google-zxing" }
gravatar = { group = "com.gravatar", name = "gravatar", version.ref = "gravatar" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jetty-webapp = { group = "org.eclipse.jetty", name = "jetty-webapp", version.ref = "jetty" }
jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jetty" }
json-path = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "json-path" }
json-smart = { group = "net.minidev", name = "json-smart", version.ref = "json-smart" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
squareup-javapoet = { module = "com.squareup:javapoet", version.ref = "squareup-javapoet" }
squareup-leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp3" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "squareup-okhttp3" }
squareup-okhttp3-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "squareup-okhttp3" }
squareup-okhttp3-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "squareup-okhttp3" }
squareup-okhttp3-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "squareup-okhttp3" }
stripe-terminal-taptopay = { group = "com.stripe", name = "stripeterminal-taptopay", version.ref = "stripe-terminal" }
stripe-terminal-core = { group = "com.stripe", name = "stripeterminal-core", version.ref = "stripe-terminal" }
stripe-terminal-ktx = { group = "com.stripe", name = "stripeterminal-ktx", version.ref = "stripe-terminal" }
tinder-statemachine = { group = "com.tinder.statemachine", name = "statemachine", version.ref = "tinder-statemachine" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
wellsql = { module = "org.wordpress:wellsql", version.ref = "wellsql" }
wellsql-processor = { module = "org.wordpress.wellsql:wellsql-processor", version.ref = "wellsql" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock", version.ref = "wiremock" }
wordpress-libaddressinput-common = { group = "org.wordpress", name = "libaddressinput.common", version.ref = "wordpress-libaddressinput" }
wordpress-lint = { module = "org.wordpress:lint", version.ref = "wordpress-lint" }
wordpress-aztec-main = { group = "org.wordpress", name = "aztec", version.ref = "wordpress-aztec" }
wordpress-aztec-glide-loader = { group = "org.wordpress.aztec", name = "glide-loader", version.ref = "wordpress-aztec" }
wordpress-utils = { group = "org.wordpress", name = "utils", version.ref = "wordpress-utils" }
zendesk-support = { group = "com.zendesk", name = "support", version.ref = "zendesk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
automattic-measure-builds = { id = "com.automattic.android.measure-builds", version.ref = "automattic-measure-builds" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
fladle = { id = "com.osacky.fladle", version.ref = "fladle" }
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }
google-protobuf = { id = "com.google.protobuf", version.ref = "google-protobuf-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
compose-screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentry" }
room = { id = "androidx.room", version.ref = "androidx-room" }
