package com.woocommerce.android.ui.payments.tracking

import com.woocommerce.android.analytics.IAnalyticsEvent

@Suppress("VariableNaming")
interface PaymentsFlowTrackerEventProvider {
    val CARD_PRESENT_ONBOARDING_LEARN_MORE_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_ONBOARDING_COMPLETED: IAnalyticsEvent
    val CARD_PRESENT_ONBOARDING_NOT_COMPLETED: IAnalyticsEvent
    val CARD_PRESENT_ONBOARDING_STEP_SKIPPED: IAnalyticsEvent
    val CARD_PRESENT_ONBOARDING_CTA_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_ONBOARDING_CTA_FAILED: IAnalyticsEvent
    val PAYMENTS_HUB_CASH_ON_DELIVERY_TOGGLED: IAnalyticsEvent
    val ENABLE_CASH_ON_DELIVERY_SUCCESS: IAnalyticsEvent
    val ENABLE_CASH_ON_DELIVERY_FAILED: IAnalyticsEvent
    val DISABLE_CASH_ON_DELIVERY_SUCCESS: IAnalyticsEvent
    val DISABLE_CASH_ON_DELIVERY_FAILED: IAnalyticsEvent
    val PAYMENTS_HUB_CASH_ON_DELIVERY_TOGGLED_LEARN_MORE_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_PAYMENT_GATEWAY_SELECTED: IAnalyticsEvent
    val CARD_READER_SOFTWARE_UPDATE_STARTED: IAnalyticsEvent
    val CARD_READER_SOFTWARE_UPDATE_ALERT_SHOWN: IAnalyticsEvent
    val CARD_READER_SOFTWARE_UPDATE_ALERT_INSTALL_CLICKED: IAnalyticsEvent
    val CARD_READER_SOFTWARE_UPDATE_FAILED: IAnalyticsEvent
    val CARD_READER_SOFTWARE_UPDATE_SUCCESS: IAnalyticsEvent
    val CARD_READER_DISCOVERY_READER_DISCOVERED: IAnalyticsEvent
    val CARD_READER_DISCOVERY_FAILED: IAnalyticsEvent
    val CARD_READER_DISCOVERY_TAPPED: IAnalyticsEvent
    val CARD_READER_AUTO_CONNECTION_STARTED: IAnalyticsEvent
    val CARD_READER_CONNECTION_TAPPED: IAnalyticsEvent
    val CARD_READER_LOCATION_SUCCESS: IAnalyticsEvent
    val CARD_READER_LOCATION_FAILURE: IAnalyticsEvent
    val CARD_READER_LOCATION_MISSING_TAPPED: IAnalyticsEvent
    val CARD_READER_CONNECTION_FAILED: IAnalyticsEvent
    val CARD_READER_CONNECTION_SUCCESS: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_PAYMENT_FAILED: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_PAYMENT_SUCCESS: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_INTERAC_PAYMENT_SUCCESS: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_INTERAC_PAYMENT_FAILED: IAnalyticsEvent
    val RECEIPT_PRINT_TAPPED: IAnalyticsEvent
    val RECEIPT_EMAIL_TAPPED: IAnalyticsEvent
    val RECEIPT_PRINT_CANCELED: IAnalyticsEvent
    val RECEIPT_PRINT_FAILED: IAnalyticsEvent
    val RECEIPT_PRINT_SUCCESS: IAnalyticsEvent
    val RECEIPT_VIEW_TAPPED: IAnalyticsEvent
    val RECEIPT_URL_FETCHING_FAILS: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_PAYMENT_CANCELLED: IAnalyticsEvent
    val PAYMENTS_FLOW_ORDER_COLLECT_PAYMENT_TAPPED: IAnalyticsEvent
    val CARD_READER_DISCONNECT_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_COLLECT_INTERAC_REFUND_CANCELLED: IAnalyticsEvent
    val CARD_PRESENT_CONNECTION_LEARN_MORE_TAPPED: IAnalyticsEvent
    val IN_PERSON_PAYMENTS_LEARN_MORE_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_SELECT_READER_TYPE_BUILT_IN_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_SELECT_READER_TYPE_BLUETOOTH_TAPPED: IAnalyticsEvent
    val MANAGE_CARD_READERS_AUTOMATIC_DISCONNECT_BUILT_IN_READER: IAnalyticsEvent
    val CARD_PRESENT_TAP_TO_PAY_NOT_AVAILABLE: IAnalyticsEvent
    val CARD_READER_AUTOMATIC_DISCONNECT: IAnalyticsEvent
    val CARD_PRESENT_PAYMENT_FAILED_CONTACT_SUPPORT_TAPPED: IAnalyticsEvent
    val CARD_PRESENT_TAP_TO_PAY_PAYMENT_FAILED_ENABLE_NFC_TAPPED: IAnalyticsEvent
    val PAYMENTS_FLOW_FAILED: IAnalyticsEvent
    val PAYMENTS_FLOW_CANCELED: IAnalyticsEvent
    val PAYMENTS_FLOW_COLLECT: IAnalyticsEvent
    val PAYMENTS_FLOW_COMPLETED: IAnalyticsEvent
    val RECEIPT_EMAIL_FAILED: IAnalyticsEvent
    val PAYMENTS_ONBOARDING_SHOWN: IAnalyticsEvent
    val PAYMENTS_ONBOARDING_DISMISSED: IAnalyticsEvent
}
