# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "💾 Create and Store Merged Manifest"
    command: .buildkite/commands/save-merged-manifest.sh
    plugins: [$CI_TOOLKIT]
