#!/bin/bash
# Stops accidental commits to master and develop. Pulled from: https://gist.github.com/stefansundin/9059706
# Install:
# cd path/to/git/repo
# curl -fL -o .git/hooks/pre-commit https://gist.githubusercontent.com/stefansundin/9059706/raw/pre-commit
# chmod +x .git/hooks/pre-commit

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "trunk" || "$BRANCH" == "develop" ]]; then
  echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
  echo "If so, commit with -n to bypass this pre-commit hook."
  exit 1
fi

# This block allows for chaining pre-commit hooks if this hook is a global hook
# (via core.hooksPath) and there also exists a repo-specific pre-commit hook
if [[ -f ".git/hooks/pre-commit" ]]; then
  type realpath >/dev/null 2>&1 # Check if realpath is available
  # If the command above failed, then we don't have realpath and we should exit
  if [ $? -ne 0 ]; then
    red='\033[0;31m'
    reset='\033[0m'

    message=$red
    message+="NOTE: the realpath binary is required to chain to the repo-specific pre-commit hook.\n\n"
    message+="On macOS, you can install it via \"brew install coreutils\".\n\n"
    message+="Ignoring."
    message+="$reset"

    echo -e $message >&2
    exit 0 # exit 0 won't fail the commit, just show the message
  fi

  if [[ "$(realpath "${BASH_SOURCE[0]}")" != "$(realpath ".git/hooks/pre-commit")" ]]; then
    .git/hooks/pre-commit
    exit $?
  fi
fi

exit 0
