import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
    alias(libs.plugins.dependency.analysis)
}

android {
    namespace = "org.wordpress.android.fluxc.plugins.woocommerce"

    defaultConfig {
        minSdkVersion gradle.ext.minSdkVersion
        targetSdkVersion gradle.ext.targetSdkVersion
        compileSdk = gradle.ext.compileSdkVersion

        room {
            schemaDirectory "$projectDir/schemas"
        }
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
        test.resources.srcDirs += files("$rootDir/libs/fluxc-tests/src/test/resources".toString())
    }

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }
    testFixtures.enable = true
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        allWarningsAsErrors = false
    }
}

dependencies {
    api project(":libs:fluxc")

    testFixturesCompileOnly project(":libs:fluxc")
    testFixturesCompileOnly libs.mockito.kotlin
    testFixturesCompileOnly libs.google.gson
    testFixturesCompileOnly libs.wordpress.utils
    testFixturesCompileOnly libs.assertj.core
    testFixturesCompileOnly libs.junit
    testFixturesCompileOnly libs.kotlinx.coroutines.core
    testFixturesCompileOnly libs.androidx.room.runtime
    testFixturesCompileOnly testFixtures(project(":libs:fluxc"))

    // WordPress libs
    implementation(libs.wordpress.utils) {
        // Using official volley package
        exclude group: "com.mcxiaoke.volley"
        exclude group: "com.android.support"
    }

    implementation libs.androidx.core.ktx

    implementation libs.wellsql
    // FluxC annotations
    api project(":libs:fluxc-annotations")
    kapt project(":libs:fluxc-processor")

    api libs.google.gson

    // Dagger
    api libs.google.dagger
    ksp libs.google.dagger.compiler
    compileOnly libs.glassfish.javax.annotation

    // Coroutines
    implementation libs.kotlinx.coroutines.core
    runtimeOnly libs.kotlinx.coroutines.android

    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler

    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.androidx.test.main.core
    testImplementation libs.assertj.core
    testImplementation libs.mockito.kotlin
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.kotlin.test.junit
    testImplementation(testFixtures(project(":libs:fluxc")))

    androidTestImplementation libs.androidx.room.testing
    androidTestRuntimeOnly libs.androidx.test.main.runner
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.assertj.core
}

dependencyAnalysis {
    issues {
        onUnusedDependencies {
            // This dependency is actually needed otherwise it will cause the app to fail to build.
            exclude(libs.androidx.core.ktx.get().module.toString())
        }
    }
}
