plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.ksp)
    alias(libs.plugins.google.dagger.hilt)
    alias(libs.plugins.dependency.analysis)
}

android {
    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    namespace = "com.woocommerce.android.pos"

    defaultConfig {
        minSdkVersion gradle.ext.minSdkVersion
        targetSdkVersion gradle.ext.targetSdkVersion
        compileSdk = gradle.ext.compileSdkVersion
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(project(":libs:commons"))
    implementation(project(":libs:fluxc"))
    implementation(project(":libs:fluxc-plugin"))
    implementation(libs.google.dagger.hilt.android.main)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.compose.ui.unit)

    ksp(libs.google.dagger.hilt.compiler)

    testImplementation(libs.junit)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.kotlin.test.junit)
    testImplementation(libs.assertj.core)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(testFixtures(project(":libs:commons")))
    testImplementation(testFixtures(project(":libs:fluxc-plugin")))
}
