package com.woocommerce.android.model

import android.os.Parcelable
import com.woocommerce.android.ui.orders.wooshippinglabels.models.ShippingLabelModel
import com.woocommerce.android.ui.orders.wooshippinglabels.models.ShippingLabelStatus
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parcelize
import org.wordpress.android.fluxc.model.shippinglabels.WCShippingLabelModel
import java.math.BigDecimal
import java.util.Date
import java.util.concurrent.TimeUnit

@Parcelize
data class ShippingLabel(
    val id: Long = 0L,
    val trackingNumber: String = "",
    val carrierId: String = "",
    val serviceName: String = "",
    val status: String = "",
    val createdDate: Date? = null,
    val expiryDate: Date? = null,
    val packageName: String = "",
    val rate: BigDecimal = BigDecimal.ZERO,
    val refundableAmount: BigDecimal = BigDecimal.ZERO,
    val currency: String = "",
    val productNames: List<String> = emptyList(),
    val productIds: List<Long> = emptyList(),
    val originAddress: Address? = null,
    val destinationAddress: Address? = null,
    val refund: Refund? = null,
    val products: List<Order.Item> = emptyList(),
    val commercialInvoiceUrl: String?
) : Parcelable {
    /**
     * Checks if a label has been anonymized.
     * An label gets anonymized when the store owner request its data to be removed from the server, for privacy reasons
     */
    @IgnoredOnParcel
    val isAnonymized: Boolean
        get() = status == "ANONYMIZED"

    @IgnoredOnParcel
    val refundExpiryDate: Date?
        get() = createdDate?.let { Date(it.time + TimeUnit.DAYS.toMillis(30)) }

    val hasCommercialInvoice
        get() = !commercialInvoiceUrl.isNullOrEmpty()

    @Parcelize
    data class Refund(
        val status: String,
        val refundDate: Date?
    ) : Parcelable
}

fun WCShippingLabelModel.WCShippingLabelRefundModel.toAppModel(): ShippingLabel.Refund {
    return ShippingLabel.Refund(
        status ?: "",
        requestDate?.let { Date(it) }
    )
}

// This function is only used to support the legacy shipping flow, such as in the order detail screen. The
// ShippingLabelModel generated by this function must not be used in the new shipping label flow.
fun ShippingLabel.toShippingLabelModel(): ShippingLabelModel {
    fun mapStatus(status: String) = when (status) {
        "PURCHASE_IN_PROGRESS" -> ShippingLabelStatus.PURCHASE_IN_PROGRESS
        "PURCHASED" -> ShippingLabelStatus.PURCHASED
        "PURCHASE_ERROR" -> ShippingLabelStatus.PURCHASE_ERROR
        "ANONYMIZED" -> ShippingLabelStatus.ANONYMIZED
        "UNKNOWN" -> ShippingLabelStatus.UNKNOWN
        else -> ShippingLabelStatus.UNKNOWN
    }

    return ShippingLabelModel(
        labelId = id,
        tracking = trackingNumber,
        refundableAmount = refundableAmount,
        status = mapStatus(status),
        created = createdDate,
        carrierId = carrierId,
        serviceName = serviceName,
        commercialInvoiceUrl = commercialInvoiceUrl,
        isCommercialInvoiceSubmittedElectronically = false, // This field is not used in the app, so we set it to false
        packageName = packageName,
        isLetter = true, // This field is not used in the app, so we set it to true
        productNames = productNames,
        productIds = productIds,
        shipmentId = null,
        receiptItemId = 0, // This field is not used in the app, so we set it to 0
        createdDate = createdDate,
        mainReceiptId = 0, // This field is not used in the app, so we set it to 0
        rate = rate,
        currency = currency,
        expiryDate = expiryDate?.time ?: 0,
        usedDate = null,
        refund = refund?.let { ShippingLabelModel.Refund(status = it.status, requestDate = it.refundDate) },
        products = products,
        originAddress = originAddress,
        destinationAddress = destinationAddress
    )
}
