package org.wordpress.android.fluxc.persistence.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing a WordPress site (WP.com, Jetpack, or self-hosted).
 *
 * **Why [id] (auto-generated) instead of [siteId] as the primary key:**
 * [siteId] is the remote WordPress.com site ID, which is `0` for pure self-hosted
 * sites that have no WP.com connection — meaning multiple self-hosted sites would
 * share the same `siteId = 0`. The auto-generated [id] serves as the local surrogate
 * key (`localSiteId`) and is referenced throughout the codebase for site lookups,
 * selected-site persistence, and as the foreign key target for WooCommerce entity
 * tables (e.g., `ProductTagEntity`, `OrderSummaryEntity`).
 */
@Entity(
    tableName = "SiteEntity",
    indices = [Index(
        value = ["siteId", "url"],
        unique = true
    )]
)
data class SiteEntity(
    @PrimaryKey(autoGenerate = true) val id: Int,
    val siteId: Long,
    val url: String,
    val adminUrl: String,
    val loginUrl: String,
    val name: String,
    val description: String,
    val isWPCom: Boolean,
    val isWPComAtomic: Boolean,
    val publishedStatus: Int,
    val isFeaturedImageSupported: Boolean,
    val isWpForTeamsSite: Boolean,
    val defaultCommentStatus: String,
    val timezone: String,
    val frameNonce: String,
    val maxUploadSize: Long,
    val memoryLimit: Long,
    val origin: Int,
    val organizationId: Int,
    val showOnFront: String,
    val pageOnFront: Long,
    val pageForPosts: Long,
    val selfHostedSiteId: Long,
    val username: String,
    val password: String,
    val xmlRpcUrl: String,
    val wpApiRestUrl: String,
    val softwareVersion: String,
    val isSelfHostedAdmin: Boolean,
    val email: String,
    val displayName: String,
    val isJetpackInstalled: Boolean,
    val isJetpackConnected: Boolean,
    val isJetpackCPConnected: Boolean,
    val jetpackVersion: String,
    val jetpackUserEmail: String,
    val isAutomatedTransfer: Boolean,
    val isWpComStore: Boolean,
    val hasWooCommerce: Boolean,
    val isVisible: Boolean,
    val isPrivate: Boolean,
    val isComingSoon: Boolean,
    val isVideoPressSupported: Boolean,
    val planId: Long,
    val planShortName: String,
    val planProductSlug: String,
    val iconUrl: String,
    val hasFreePlan: Boolean,
    val unmappedUrl: String,
    val webEditor: String,
    val mobileEditor: String,
    val hasCapabilityEditPages: Boolean,
    val hasCapabilityEditPosts: Boolean,
    val hasCapabilityEditOthersPosts: Boolean,
    val hasCapabilityEditOthersPages: Boolean,
    val hasCapabilityDeletePosts: Boolean,
    val hasCapabilityDeleteOthersPosts: Boolean,
    val hasCapabilityEditThemeOptions: Boolean,
    val hasCapabilityEditUsers: Boolean,
    val hasCapabilityListUsers: Boolean,
    val hasCapabilityManageCategories: Boolean,
    val hasCapabilityManageOptions: Boolean,
    val hasCapabilityActivateWordads: Boolean,
    val hasCapabilityPromoteUsers: Boolean,
    val hasCapabilityPublishPosts: Boolean,
    val hasCapabilityUploadFiles: Boolean,
    val hasCapabilityDeleteUser: Boolean,
    val hasCapabilityRemoveUsers: Boolean,
    val hasCapabilityViewStats: Boolean,
    val spaceAvailable: Long,
    val spaceAllowed: Long,
    val spaceUsed: Long,
    val spacePercentUsed: Double,
    val activeModules: String,
    val isPublicizePermanentlyDisabled: Boolean,
    val activeJetpackConnectionPlugins: String,
    val jetpackModules: String,
    val zendeskPlan: String,
    val zendeskAddOns: String,
    val isBloggingPromptsOptedIn: Boolean,
    val isBloggingPromptsCardOptedIn: Boolean,
    val isPotentialBloggingSite: Boolean,
    val isBloggingReminderOnMonday: Boolean,
    val isBloggingReminderOnTuesday: Boolean,
    val isBloggingReminderOnWednesday: Boolean,
    val isBloggingReminderOnThursday: Boolean,
    val isBloggingReminderOnFriday: Boolean,
    val isBloggingReminderOnSaturday: Boolean,
    val isBloggingReminderOnSunday: Boolean,
    val bloggingReminderHour: Int,
    val bloggingReminderMinute: Int,
    val applicationPasswordsAuthorizeUrl: String,
    val canBlaze: Boolean,
    val planActiveFeatures: String,
    val wasEcommerceTrial: Boolean?,
    val isSingleUserSite: Boolean?,
    val isGardenSite: Boolean,
    val gardenName: String,
    val gardenPartner: String,
)
