import com.android.build.api.dsl.ManagedVirtualDevice

plugins {
    alias(libs.plugins.android.test)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.androidx.baselineprofile)
    alias(libs.plugins.firebase.testlab)
}

android {
    namespace 'com.woocommerce.android.baselineprofile'
    compileSdk gradle.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    defaultConfig {
        minSdk 28 // Cant use current "gradle.ext.minSdkVersion", which points to 26, because various calls requires API level 28.
        targetSdk gradle.ext.targetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ":WooCommerce"

    flavorDimensions += ["buildType"]
    productFlavors {
        vanilla { dimension = "buildType" }
    }

    // This code creates the gradle managed device used to generate baseline profiles.
    // To use GMD please invoke generation through the command line:
    // ./gradlew :WooCommerce:generateVanillaReleaseBaselineProfile
    testOptions.managedDevices.devices {
        pixel6Api34(ManagedVirtualDevice) {
            device = "Pixel 6"
            apiLevel = 34
            systemImageSource = "google"
        }
    }
}

def directory = "/storage/emulated/0/Android/media/${android.namespace}"
firebaseTestLab {
    serviceAccountCredentials = rootProject.file(".configure-files/firebase.secrets.json")
    managedDevices {
        "ftlDeviceTokay35" {
            device = "tokay"
            apiLevel = 35
        }
    }
    testOptions {
        results {
            directoriesToPull.addAll(directory.toString())
            recordVideo = true
            performanceMetrics = true
        }
    }
}

// This is the configuration block for the Baseline Profile plugin.
// You can specify to run the generators on a managed devices or connected devices.
baselineProfile {
    managedDevices += "ftlDeviceTokay35"
    useConnectedDevices = false
}

dependencies {
    implementation libs.androidx.test.ext.junit
    implementation libs.androidx.test.espresso.core
    implementation libs.androidx.test.uiautomator
    implementation libs.androidx.benchmark.macro.junit4
}

androidComponents {
    onVariants(selector().all()) { v ->
        def artifactsLoader = v.artifacts.getBuiltArtifactsLoader()
        v.instrumentationRunnerArguments.put(
                "targetAppId",
                v.testedApks.map { artifactsLoader.load(it)?.applicationId }
        )
    }
}
