package com.woocommerce.android.datastore

enum class DataStoreType {
    TRACKER,
    ANALYTICS_UI_CACHE,
    ANALYTICS_CONFIGURATION,
    DASHBOARD_STATS,
    TOP_PERFORMER_PRODUCTS,
    COUPONS,
    LAST_UPDATE,
    SITE_PICKER_WOO_VISIBLE_SITES,
    SHIPPING_LABEL_CONFIGURATION,
    SHIPPING_LABEL_ADDRESS
}
