#!/bin/bash
set -euo pipefail

#echo "--- :rubygems: Setting up Gems"
#install_gems

#echo "--- :closed_lock_with_key: Installing Secrets"
#bundle exec fastlane run configure_apply

#if [[ "$BUILDKITE_PIPELINE_SLUG" == "woocommerce-android" && "$BUILDKITE_STEP_KEY" == "unit_tests" ]]; then
export BUILDKITE_ANALYTICS_TOKEN="12341234"
#fi
