package com.woocommerce.android.ui.orders.shippinglabels.creation

/***
 *   AIR_ELIGIBLE_ETHANOL: 'Air Eligible Ethanol Package - (authorized fragrance and hand sanitizer shipments)',
 *   CLASS_1: 'Class 1 – Toy Propellant/Safety Fuse Package',
 *   CLASS_3: 'Class 3 - Package (Hand sanitizer, rubbing alcohol, ethanol base products, flammable liquids etc.)',
 *   CLASS_4: 'Class 4 - Package (Flammable solids)',
 *   CLASS_5: 'Class 5 - Package (Oxidizers)',
 *   CLASS_6: 'Class 6 - Package (Poisonous materials)',
 *   CLASS_7: 'Class 7 – Radioactive Materials Package (e.g., smoke detectors, minerals, gun sights, etc.)',
 *   CLASS_8_CORROSIVE: 'Class 8 – Corrosive Materials Package - Air Eligible Corrosive Materials (certain cleaning or tree/weed killing compounds, etc.)',
 *   CLASS_8_WET_BATTERY: 'Class 8 – Nonspillable Wet Battery Package - Sealed lead acid batteries',
 *   CLASS_9_NEW_LITHIUM_INDIVIDUAL: 'Class 9 - Lithium Battery Marked – Ground Only Package - New Individual or spare lithium batteries (marked UN3480 or UN3090)',
 *   CLASS_9_USED_LITHIUM: 'Class 9 - Lithium Battery – Returns Package - Used electronic devices containing or packaged with lithium batteries (markings required)',
 *   CLASS_9_NEW_LITHIUM_DEVICE: 'Class 9 - Lithium batteries, marked package - New electronic devices packaged with lithium batteries (marked UN3481 or UN3091)',
 *   CLASS_9_DRY_ICE: 'Class 9 – Dry Ice Package (limited to 5 lbs. if shipped via Air)',
 *   CLASS_9_UNMARKED_LITHIUM: 'Class 9 – Lithium batteries, unmarked package - New electronic devices installed or packaged with lithium batteries (no marking)',
 *   CLASS_9_MAGNETIZED: 'Class 9 – Magnetized Materials Package',
 *   DIVISION_4_1: 'Division 4.1 – Mailable flammable solids and Safety Matches Package - Safety/strike on box matches, book matches, mailable flammable solids',
 *   DIVISION_5_1: 'Division 5.1 – Oxidizers Package - Hydrogen peroxide (8 to 20% concentration)',
 *   DIVISION_5_2: 'Division 5.2 – Organic Peroxides Package',
 *   DIVISION_6_1: 'Division 6.1 – Toxic Materials Package (with an LD50 of 50 mg/kg or less) - (pesticides, herbicides, etc.)',
 *   DIVISION_6_2: 'Division 6.2 - Hazardous Materials - Biological Materials (e.g., lab test kits, authorized COVID test kit returns)',
 *   EXCEPTED_QUANTITY_PROVISION: 'Excepted Quantity Provision Package (e.g., small volumes of flammable liquids, corrosive, toxic or environmentally hazardous materials - marking required)',
 *   GROUND_ONLY: 'Ground Only Hazardous Materials (For items that are not listed, but are restricted to surface only)',
 *   ID8000: 'ID8000 Consumer Commodity Package - Air Eligible ID8000 Consumer Commodity (Non-flammableaerosols, Flammable combustible liquids, Toxic Substance, Miscellaneious hazardous materials)',
 *   LIGHTERS: 'Lighters Package - Authorized Lighters',
 *   LIMITED_QUANTITY: 'LTD QTY Ground Package - Aerosols, spray disinfectants, spray paint, hair spray, propane, butane, cleaning products, etc. - Fragrances, nail polish, nail polish remover, solvents, hand sanitizer, rubbing alcohol, ethanol base products, etc. - Other limited quantity surface materials (cosmetics, cleaning products, paints, etc.)',
 *   SMALL_QUANTITY_PROVISION: 'Small Quantity Provision Package (markings required)',
 * };
 */
enum class ShippingLabelHazmatCategory {
    AIR_ELIGIBLE_ETHANOL,
    CLASS_1,
    CLASS_3,
    CLASS_4,
    CLASS_5,
    CLASS_6,
    CLASS_7,
    CLASS_8_CORROSIVE,
    CLASS_8_WET_BATTERY,
    CLASS_9_NEW_LITHIUM_INDIVIDUAL,
    CLASS_9_USED_LITHIUM,
    CLASS_9_NEW_LITHIUM_DEVICE,
    CLASS_9_DRY_ICE,
    CLASS_9_UNMARKED_LITHIUM,
    CLASS_9_MAGNETIZED,
    DIVISION_4_1,
    DIVISION_5_1,
    DIVISION_5_2,
    DIVISION_6_1,
    DIVISION_6_2,
    EXCEPTED_QUANTITY_PROVISION,
    GROUND_ONLY,
    ID8000,
    LIGHTERS,
    LIMITED_QUANTITY,
    SMALL_QUANTITY_PROVISION
}
