#!/usr/bin/env python3
"""Generate Maestro string environment variables from Android strings.xml."""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


FORMAT_RE = re.compile(r"%(?:\d+\$)?[dsf]")
NON_WORD_RE = re.compile(r"[^A-Za-z0-9]+")


def env_name(prefix: str, key: str) -> str:
    normalized = NON_WORD_RE.sub("_", key).strip("_").upper()
    return f"{prefix}_{normalized}"


def text_content(element: ET.Element) -> str:
    return "".join(element.itertext()).strip()


def unescape_android(value: str) -> str:
    return (
        value.replace("\\'", "'")
        .replace('\\"', '"')
        .replace("\\n", "\n")
        .replace("\\@", "@")
        .replace("\\?", "?")
    )


def to_regex(value: str) -> str:
    parts: list[str] = []
    last = 0
    for match in FORMAT_RE.finditer(value):
        parts.append(re.escape(value[last : match.start()]))
        parts.append(".*")
        last = match.end()
    parts.append(re.escape(value[last:]))
    return "".join(parts)


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'").replace("\n", "\\n") + "'"


def generate(strings_xml: Path, output: Path, prefix: str) -> None:
    root = ET.parse(strings_xml).getroot()
    lines = [
        "# Generated by .maestro/scripts/generate-strings-env.py",
        f"# Source: {strings_xml}",
        "",
    ]
    parameterized: list[str] = []

    for item in root.findall("string"):
        name = item.attrib.get("name")
        if not name or item.attrib.get("translatable") == "false":
            continue
        value = unescape_android(text_content(item))
        if not value:
            continue
        variable = env_name(prefix, name)
        if FORMAT_RE.search(value):
            lines.append(f"{variable}_RE={shell_quote(to_regex(value))}")
            parameterized.append(variable)
        else:
            lines.append(f"{variable}={shell_quote(value)}")

    for plural in root.findall("plurals"):
        name = plural.attrib.get("name")
        if not name:
            continue
        for item in plural.findall("item"):
            quantity = item.attrib.get("quantity")
            if not quantity:
                continue
            value = unescape_android(text_content(item))
            variable = env_name(prefix, f"{name}_{quantity}_RE")
            lines.append(f"{variable}={shell_quote(to_regex(value))}")

    if parameterized:
        lines.extend(
            [
                "",
                "# Parameterized strings intentionally emit only *_RE variables.",
                "# Do not assert raw % placeholders in flows.",
            ]
        )
        for variable in parameterized:
            lines.append(f"# {variable} -> {variable}_RE")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def verify_no_parameterized_literal_references(output: Path, flows_dir: Path) -> None:
    env_text = output.read_text(encoding="utf-8")
    parameterized = {
        line.split(" -> ", 1)[0].removeprefix("# ")
        for line in env_text.splitlines()
        if line.startswith("# STRING_") and " -> " in line
    }
    if not parameterized:
        return
    errors: list[str] = []
    for flow in flows_dir.glob("*.yaml"):
        text = flow.read_text(encoding="utf-8")
        for variable in sorted(parameterized):
            if "${" + variable + "}" in text:
                errors.append(f"{flow}: references parameterized literal {variable}; use {variable}_RE")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        raise SystemExit(1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strings-xml",
        default="WooCommerce/src/main/res/values/strings.xml",
        type=Path,
    )
    parser.add_argument("--output", default=".maestro/strings.env", type=Path)
    parser.add_argument("--flows-dir", default=".maestro/flows", type=Path)
    parser.add_argument("--prefix", default="STRING")
    parser.add_argument("--check-flow-references", action="store_true")
    args = parser.parse_args()

    generate(args.strings_xml, args.output, args.prefix)
    if args.check_flow_references:
        verify_no_parameterized_literal_references(args.output, args.flows_dir)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
