# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  - label: "Download Release Translations"
    plugins: [$CI_TOOLKIT]
    command: |
      # echo '--- :robot_face: Use bot for git operations'
      # source use-bot-for-git

      git fetch origin iangmaia/test-mac-metal
      git checkout iangmaia/test-mac-metal
      git pull --rebase

      echo '--- :pencil: Updating pt-BR changelog'
      echo "Atualização do changelog para pt-BR em $(date)" > ./fastlane/metadata/android/pt-BR/changelogs/default.txt

      echo '--- :rocket: Committing and pushing changes'
      git add ./fastlane/metadata/android/pt-BR/changelogs/default.txt
      git commit -m "Update pt-BR changelog [ci skip]"
      git push origin iangmaia/test-mac-metal
    agents:
        queue: mac-metal
    retry:
      manual:
        # If those jobs fail, one should always prefer re-triggering a new build from Releases V2 rather than retrying the individual job from Buildkite
        allowed: false
