steps:
  - label: "Finalize Hotfix Release"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :git: Checkout Release Branch'
      .buildkite/commands/checkout-release-branch.sh

      echo '--- :fire: Finalize Hotfix Release'
      bundle exec fastlane finalize_hotfix_release skip_confirm:true include_wear_app:"${INCLUDE_WEAR_APP:-false}"
