# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  - label: " Start Code Freeze"
    plugins: [$CI_TOOLKIT]
    command: |
      echo '--- :robot_face: Use bot for git operations'
      source use-bot-for-git

      echo '--- :ruby: Setup Ruby Tools'
      install_gems

      echo '--- :snowflake: Start Code Freeze'
      bundle exec fastlane start_code_freeze skip_confirm:true
    agents:
        queue: "tumblr-metal"
    retry:
      manual:
        # If those jobs fail, one should always prefer re-triggering a new build from ReleaseV2 rather than retrying the individual job from Buildkite
        allowed: false
