plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.dependency.analysis)
}

android {
    namespace = "com.woocommerce.android.ui.compose.designsystem"
    compileSdk = gradle.ext.compileSdkVersion

    defaultConfig {
        minSdk = gradle.ext.minSdkVersion
        targetSdk = gradle.ext.targetSdkVersion
    }

    compileOptions {
        sourceCompatibility = libs.versions.java.get()
        targetCompatibility = libs.versions.java.get()
    }

    buildFeatures {
        buildConfig = false
        compose = true
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui.main)
    implementation(libs.androidx.compose.ui.tooling.preview)
    debugImplementation(libs.androidx.compose.ui.tooling.main)
}
