name: Submit dependencies to GitHub Dependency Graph
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: cp gradle.properties-example gradle.properties
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/dependency-submission@v3
      - name: Perform dependency review
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v4
        with:
          license-check: false
          comment-summary-in-pr: always
          warn-only: true
