name: Auto-merge Dependabot PATCH updates

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'woocommerce/woocommerce-android'
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Assign closest open milestone to PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          set -e
          title=$(gh api repos/$GITHUB_REPOSITORY/milestones \
            --jq '[.[]
              | select(.state=="open" and .due_on!=null and (.due_on | fromdateiso8601) >= now)
            ]
            | sort_by(.due_on)
            | .[0].title')

          if [ -n "$title" ]; then
            echo "Assigning milestone '$title' to PR #${{ github.event.pull_request.number }}"
            gh pr edit "${{ github.event.pull_request.number }}" --milestone "$title"
          else
            echo "No future open milestones found."
          fi

      - name: Approve the PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          set -e
          gh pr review --approve "$PR_URL"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          set -e
          gh pr merge --auto --merge "$PR_URL"
